### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by lightfirst** [MrColdbird/aemu#12]
On https://pro.coldbird.net/status/status.xml, the URL for "Community Forum" is "https://forum.coldbird.net/" now not http://forum.prometheus.uk.to/
Client Download URL is https://forum.coldbird.net/viewtopic.php?f=2&t=23  not http://forum.prometheus.uk.to/viewtopic.php?f=2&t=23

**Comment by belldandu** [comment]
I apologize for the delay @lightfirst im not even sure myself why i didnt do this in my previous pull request.
