### ISSUE TITLE
coldbird Server down !!

### ISSUE THREAD

**Issue by lightfirst** [MrColdbird/aemu#7]
whenever i visit the status page, this is what i see
![2016_1_25_0_25_12_384_pm](https://cloud.githubusercontent.com/assets/4612168/12814030/e990bb8c-cb76-11e5-856d-a89f4ca5a2c0.png)

**Comment by lightfirst** [comment]
BTW, could coldbird server also show user name, I can find it on source
It will be helpful if coldbird can show both game name, group name and users.
![p](https://cloud.githubusercontent.com/assets/4612168/12814157/dfa7e130-cb77-11e5-9312-50ff16c78a5a.PNG)

**Comment by belldandu** [comment]
@lightfirst your second post should really be in a different issue ...

also this needs to be closed as it was already fixed.
